#!/usr/bin/env python3
"""Create Paperclip issues for GoodLendPool + ValidatorStaking bugs."""
import sys, json
sys.path.insert(0, '/home/goodclaw/gooddollar-l2')
import pc_api

COMPANY = '7e8ba4ed-e545-4394-ad98-c0c855409a4e'
AGENT   = 'b67dca66-0fa7-4ed5-9c94-7d02d4ecd832'

# Issue 1: GoodLendPool stale health factor check
desc1 = "\n".join([
    "## Summary",
    "",
    "`_calculateHealthFactor()` in `GoodLendPool` reads `reserve.liquidityIndex` and",
    "`reserve.variableBorrowIndex` directly from storage for ALL reserves. For reserves",
    "that haven't had `_updateState()` called recently, both indexes are stale.",
    "Because borrow interest compounds faster than supply interest, stale indexes",
    "OVERSTATE the health factor — making a position look healthier than it is.",
    "",
    "## Bug",
    "",
    "`src/lending/GoodLendPool.sol:656-693` (`_calculateHealthFactor`):",
    "```solidity",
    "uint256 collateral = _gTokenBalance(asset, user, reserve.liquidityIndex);   // stale",
    "uint256 debt       = _debtBalance(asset, user, reserve.variableBorrowIndex); // stale",
    "```",
    "",
    "`borrow()` only calls `_updateState(borrowedAsset)`, so when HF is checked,",
    "collateral reserves and OTHER debt reserves are still stale.",
    "",
    "## Impact",
    "",
    "A borrower at the HF=1.0 boundary can borrow slightly more than safe because",
    "their debt across other reserves is understated. The position would be",
    "immediately under-collateralized after the next `_updateState()` on those reserves.",
    "",
    "## Fix",
    "",
    "Use the view-friendly `getLiquidityIndex()` / `getBorrowIndex()` helpers (which",
    "simulate pending interest) inside `_calculateHealthFactor`, or call `_updateState`",
    "for all reserves before the HF check in `borrow()` and `withdraw()`.",
    "",
    "```solidity",
    "// Instead of reserve.liquidityIndex:",
    "uint256 idx = getLiquidityIndex(asset);",
    "uint256 bidx = getBorrowIndex(asset);",
    "```",
    "",
    "## File",
    "",
    "- `src/lending/GoodLendPool.sol:674` — collateral balance uses stale liquidityIndex",
    "- `src/lending/GoodLendPool.sol:682` — debt balance uses stale variableBorrowIndex",
])

body1 = {
    'title': 'bug(lending): _calculateHealthFactor uses stale per-reserve indexes — HF overstated at borrow time',
    'description': desc1,
    'status': 'todo',
    'priority': 'high',
    'companyId': COMPANY,
    'assigneeAgentId': AGENT,
}

# Issue 2: GoodLendPool unchecked transferFrom
desc2 = "\n".join([
    "## Summary",
    "",
    "`GoodLendPool` calls `IERC20.transferFrom()` in 6 places without checking the",
    "boolean return value. For non-reverting ERC20 tokens, a failed transfer is",
    "silently ignored, allowing operations to proceed with no actual token movement.",
    "",
    "## Bug",
    "",
    "All unchecked calls in `src/lending/GoodLendPool.sol`:",
    "",
    "| Line | Function    | Call |",
    "|------|-------------|------|",
    "| 225  | supply      | `transferFrom(user, gToken, amount)` — user deposit lost |",
    "| 260  | withdraw    | `transferFrom(gToken, user, amount)` — user receives nothing |",
    "| 297  | borrow      | `transferFrom(gToken, user, amount)` — user gets nothing but accrues debt |",
    "| 331  | repay       | `transferFrom(user, gToken, amount)` — repay silently fails but debt is burned |",
    "| 395  | liquidate   | `transferFrom(liquidator, gToken, debtToCover)` — free liquidation |",
    "| 403  | liquidate   | `transferFrom(gToken, liquidator, collateral)` — free collateral |",
    "| 433  | flashLoan   | `transferFrom(gToken, receiver, amount)` — receiver gets nothing |",
    "| 442  | flashLoan   | `transferFrom(receiver, gToken, amount+premium)` — free flash loan |",
    "",
    "## Impact",
    "",
    "Most severe: `repay` (line 331) silently clears debt without collecting tokens.",
    "A non-reverting token could be used to wipe borrowings for free.",
    "Also: `liquidate` line 395 — liquidator pays no debt but burns user's debt tokens.",
    "",
    "## Fix",
    "",
    "Wrap all calls with a return-value check:",
    "```solidity",
    "if (!IERC20(asset).transferFrom(from, to, amount)) revert TransferFailed();",
    "```",
    "",
    "Add `error TransferFailed();` to the contract.",
    "",
    "## Files",
    "",
    "- `src/lending/GoodLendPool.sol:225,260,297,331,395,403,433,442`",
])

body2 = {
    'title': 'bug(lending): GoodLendPool 8x unchecked IERC20.transferFrom — free repay/liquidate/flash loan possible',
    'description': desc2,
    'status': 'todo',
    'priority': 'critical',
    'companyId': COMPANY,
    'assigneeAgentId': AGENT,
}

# Issue 3: ValidatorStaking reward drain
desc3 = "\n".join([
    "## Summary",
    "",
    "`ValidatorStaking.claimRewards()` pays staking rewards from the contract's G$",
    "balance, which consists entirely of other validators' staked G$. There is no",
    "external reward-funding mechanism. Validators claiming rewards reduce the",
    "available balance for other validators' withdrawals.",
    "",
    "## Bug",
    "",
    "`src/ValidatorStaking.sol:226-235` (`claimRewards`):",
    "```solidity",
    "uint256 rewards = pendingRewards(msg.sender);",
    "// ...",
    "goodDollar.transfer(msg.sender, rewards);  // draws from staked G$ pool",
    "```",
    "",
    "The 5% APY reward (line 219, `rewardRateBPS = 500`) is paid from the same",
    "pool that holds staked G$. No `fundRewards()` inflow exists.",
    "",
    "## Impact",
    "",
    "If 10 validators each stake 1M G$ (10M total), after 1 year of rewards:",
    "- Reward claims total: 10M * 5% = 500k G$",
    "- Contract balance drops from 10M to 9.5M",
    "- Last validators to withdraw after reward claims may receive less than staked",
    "- `slash()` calling `fundUBIPool(slashAmount)` could also revert if balance insufficient",
    "",
    "## Fix",
    "",
    "Options:",
    "1. Fund rewards from protocol fee flow (UBIFeeSplitter route to this contract)",
    "2. Mint rewards via `GoodDollarToken.mint()` (inflation-funded)",
    "3. Cap rewards to available non-staked balance",
    "",
    "At minimum, add a balance check so `claimRewards` reverts cleanly rather",
    "than draining other validators' principal:",
    "```solidity",
    "require(goodDollar.balanceOf(address(this)) >= totalStaked + rewards,",
    "    'Insufficient reward reserve');",
    "```",
    "",
    "## File",
    "",
    "- `src/ValidatorStaking.sol:226-235` — claimRewards pays from staked pool",
    "- `src/ValidatorStaking.sol:205` — slash may also underflow if rewards drained pool",
])

body3 = {
    'title': 'bug(staking): ValidatorStaking rewards drawn from staked pool — no reward reserve mechanism',
    'description': desc3,
    'status': 'todo',
    'priority': 'high',
    'companyId': COMPANY,
    'assigneeAgentId': AGENT,
}

for i, body in enumerate([body1, body2, body3], 1):
    r = pc_api.api('POST', '/companies/' + COMPANY + '/issues', body)
    print("Issue", i, ":", r.get('identifier', '?'), '--', r.get('id', '?'), '--', r.get('error', 'ok'))
