#!/usr/bin/env python3
"""Create Paperclip issues for LiFiBridgeAggregator + SwapPriceOracle bugs."""
import sys, json
sys.path.insert(0, '/home/goodclaw/gooddollar-l2')
import pc_api

# Issue 1: completeSwap minDestAmount not enforced
desc1 = "\n".join([
    "## Summary",
    "",
    "`completeSwap()` in `LiFiBridgeAggregator` records a swap as completed but never",
    "validates that `destAmount >= minDestAmount`. Users' slippage protection is purely",
    "off-chain — a keeper can confirm a swap with 0 or any arbitrary destAmount.",
    "",
    "## Bug",
    "",
    "`src/swap/LiFiBridgeAggregator.sol:276-289`:",
    "",
    "```solidity",
    "function completeSwap(",
    "    uint256 swapId,",
    "    bytes32 lifiTxHash,",
    "    uint256 destAmount   // keeper-supplied, never validated",
    ") external onlyKeeper {",
    "    SwapRequest storage s = swaps[swapId];",
    "    // ...",
    "    s.status = SwapStatus.Completed;  // s.minDestAmount never checked!",
    "}",
    "```",
    "",
    "`s.minDestAmount` is stored in `SwapRequest` but never read in `completeSwap`.",
    "",
    "## Impact",
    "",
    "- A malicious or buggy keeper can confirm a swap with destAmount=0",
    "- Swap is permanently marked Completed with no recourse for the user",
    "- Users lose slippage protection they explicitly set",
    "",
    "## Fix",
    "",
    "```solidity",
    "error SlippageExceeded(uint256 got, uint256 min);",
    "",
    "// In completeSwap, before s.status = Completed:",
    "if (destAmount < s.minDestAmount) revert SlippageExceeded(destAmount, s.minDestAmount);",
    "```",
    "",
    "## File",
    "",
    "- `src/swap/LiFiBridgeAggregator.sol:283` — add minDestAmount enforcement",
])

body1 = {
    'title': 'bug(swap): completeSwap never enforces minDestAmount — slippage protection off-chain only',
    'description': desc1,
    'status': 'todo',
    'priority': 'high',
    'companyId': '7e8ba4ed-e545-4394-ad98-c0c855409a4e',
    'assigneeAgentId': 'b67dca66-0fa7-4ed5-9c94-7d02d4ecd832',
}

# Issue 2: Missing ERC20 transfer return value checks
desc2 = "\n".join([
    "## Summary",
    "",
    "`LiFiBridgeAggregator` calls `IERC20.transfer()` in three places without checking",
    "the return value. For non-reverting tokens (e.g., USDT), a failed transfer silently",
    "succeeds at the contract level.",
    "",
    "## Bug",
    "",
    "Three unchecked calls in `src/swap/LiFiBridgeAggregator.sol`:",
    "",
    "1. Line 199 — `IERC20(srcToken).transfer(ubiFeeSplitter, fee)` in `initiateSwap`",
    "   - If this fails silently, UBI fee is lost; user swap proceeds normally",
    "2. Line 307 — `IERC20(s.srcToken).transfer(s.user, s.srcAmount)` in `refundSwap`",
    "   - If this fails silently, user is never refunded but swap marked `Refunded`",
    "3. Line 328 — `IERC20(s.srcToken).transfer(s.user, s.srcAmount)` in `expireSwap`",
    "   - Same as above — user loses funds on expiry",
    "",
    "## Impact",
    "",
    "For tokens that return `false` instead of reverting (USDT mainnet, BNB, etc.):",
    "- Users can lose entire swap amounts on refund/expiry",
    "- UBI fees silently vanish",
    "",
    "## Fix",
    "",
    "Use `require(IERC20(...).transfer(...))` or the OpenZeppelin SafeERC20 pattern:",
    "",
    "```solidity",
    "bool ok = IERC20(srcToken).transfer(ubiFeeSplitter, fee);",
    "if (!ok) revert TransferFailed();",
    "```",
    "",
    "Apply to all three call sites.",
    "",
    "## Files",
    "",
    "- `src/swap/LiFiBridgeAggregator.sol:199` — UBI fee transfer in initiateSwap",
    "- `src/swap/LiFiBridgeAggregator.sol:307` — refund transfer in refundSwap",
    "- `src/swap/LiFiBridgeAggregator.sol:328` — refund transfer in expireSwap",
])

body2 = {
    'title': 'bug(swap): unchecked ERC20 transfer return values in LiFiBridgeAggregator (3 sites)',
    'description': desc2,
    'status': 'todo',
    'priority': 'high',
    'companyId': '7e8ba4ed-e545-4394-ad98-c0c855409a4e',
    'assigneeAgentId': 'b67dca66-0fa7-4ed5-9c94-7d02d4ecd832',
}

# Issue 3: SwapPriceOracle TWAP division by wrong elapsed
desc3 = "\n".join([
    "## Summary",
    "",
    "`getTWAP()` in `SwapPriceOracle` divides the cumulative price*time accumulator by",
    "`block.timestamp - twapTimestamp` — but `twapTimestamp` is reset to `block.timestamp`",
    "on EVERY price update. This makes the divisor equal to only the time since the",
    "last update, causing wildly inflated TWAP values whenever multiple updates occurred.",
    "",
    "## Bug",
    "",
    "`src/oracle/SwapPriceOracle.sol:227-235`:",
    "",
    "```solidity",
    "function getTWAP(address token) external view returns (uint256) {",
    "    PriceData storage pd = prices[token];",
    "    uint256 elapsed = block.timestamp - pd.twapTimestamp; // WRONG: resets on each update",
    "    uint256 cumWithCurrent = pd.twapCumulative + pd.price * (block.timestamp - pd.timestamp);",
    "    return cumWithCurrent / elapsed;  // numerator spans full history, denominator = last interval only",
    "}",
    "```",
    "",
    "`_updateTWAP()` sets `pd.twapTimestamp = block.timestamp` (line 287), so after",
    "any price update: `elapsed = now - lastUpdate` ≠ total TWAP window.",
    "",
    "## Example",
    "",
    "- t=0: price=100",
    "- t=10: updatePrice(200) → twapCumulative = 100*10 = 1000; twapTimestamp = 10",
    "- t=15: getTWAP() → elapsed=5; cumWithCurrent=1000+200*5=2000; TWAP=2000/5=**400**",
    "- Correct TWAP over full 15s = (100*10 + 200*5)/15 = **133**",
    "",
    "## Fix",
    "",
    "Track `twapStartTime` separately (set only on first price), and use it as the",
    "divisor baseline in `getTWAP`. Or accept a `windowStart` parameter:",
    "",
    "```solidity",
    "function getTWAP(address token, uint256 windowStart) external view returns (uint256) {",
    "    // elapsed = block.timestamp - windowStart",
    "    // cumWithCurrent / elapsed where cumWithCurrent accounts for windowStart",
    "}",
    "```",
    "",
    "## File",
    "",
    "- `src/oracle/SwapPriceOracle.sol:227-235` — getTWAP uses wrong elapsed divisor",
    "- `src/oracle/SwapPriceOracle.sol:281-287` — _updateTWAP resets twapTimestamp incorrectly",
])

body3 = {
    'title': 'bug(oracle): SwapPriceOracle TWAP divides by wrong time window — inflated values after multi-update',
    'description': desc3,
    'status': 'todo',
    'priority': 'medium',
    'companyId': '7e8ba4ed-e545-4394-ad98-c0c855409a4e',
    'assigneeAgentId': 'b67dca66-0fa7-4ed5-9c94-7d02d4ecd832',
}

for i, body in enumerate([body1, body2, body3], 1):
    r = pc_api.api('POST', '/companies/7e8ba4ed-e545-4394-ad98-c0c855409a4e/issues', body)
    print(f"Issue {i}: {r.get('identifier', '?')} — {r.get('id', '?')} — {r.get('error', 'ok')}")
